services:
  db:
    image: postgres:15
    container_name: mydb
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/myapp
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3001:80"

volumes:
  db_data:
